### PR TITLE
fix: split once to preserve other `-`

### LINKED ISSUE #436: sycamore link
The sycamore link shown in the section `Choose your UI template` is wrong the shown link is [https://sycamorers.netlify.app](https://sycamorers.netlify.app), while the real link is [https://sycamore-rs.netlify.app/](https://sycamore-rs.netlify.app/).

### PR DESCRIPTION
**Pull request by amrbashir**
closes #436

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [ ] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/create-tauri-app/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: packages/cli/src/theme.rs [hunk 1]
```diff
@@ -279,9 +279,7 @@ impl Theme for ColorfulTheme {
         text: &str,
         active: bool,
     ) -> fmt::Result {
-        let mut s = text.split('-');
-        let text = s.next().unwrap();
-        let desc = s.collect::<String>();
+        let (text, desc) = text.split_once('-').unwrap_or_else(|| (text, ""));
```
Comment (amrbashir) [inline packages/cli/src/theme.rs]:
```suggestion
        let (text, desc) = text.split_once('-').unwrap_or((text, ""));
```
