### PR TITLE
fix(cli): fixed to_valid_pkg_name (fix #262)

### LINKED ISSUE #262: Automatic correction of package names does not meet expectations
The cli tool will try to fix bad package names the first time, but only the first character.
create-tauri-app-fix-name-bug

### PR DESCRIPTION
**Pull request by alanxmay**
### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/create-tauri-app/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

File: packages/cli/src/lib.rs [hunk 1]
```diff
@@ -241,7 +241,7 @@ fn to_valid_pkg_name(project_name: &str) -> String {
         .replace('\\', "")
         .replace('/', "");
 
-    if let Some(ch) = ret.chars().next() {
+    for ch in ret.clone().chars() {
         if ch.is_ascii_digit() || ch == '-' {
             ret.remove(0);
         }
```
Comment (amrbashir) [inline packages/cli/src/lib.rs]: we only need to remove the leading numbers and `-`; this however will remove the first character no matter what it is whenever a number is encountered in the iteration; instead, we want to find the index of the first character that is not a number nor a `-` and remove until it.

**Review by amrbashir — CHANGES_REQUESTED** [review]
Thank you for your contribution but this still doesn't fix the issue.

File: packages/cli/src/lib.rs (hunk 1 above)
Comment (alanxmay) [reply packages/cli/src/lib.rs]: Thanks for pointing out the problem, I'll fix it.

Comment (alanxmay) [reply packages/cli/src/lib.rs]: Done, passed all tests.

Comment (alanxmay) [reply packages/cli/src/lib.rs]: In addition, I added another commit, which added more tests.

File: packages/cli/src/lib.rs [hunk 2]
```diff
@@ -241,11 +241,10 @@ fn to_valid_pkg_name(project_name: &str) -> String {
...
         .replace('/', "");
 
-    if let Some(ch) = ret.chars().next() {
-        if ch.is_ascii_digit() || ch == '-' {
-            ret.remove(0);
-        }
-    }
+    let ret = ret
+        .chars()
+        .skip_while(|ch| ch.is_ascii_digit() || *ch == '-')
```
Comment (amrbashir) [inline packages/cli/src/lib.rs:246]: this will still remove all numbers and `-` and we only want to remove the leading. Here is some test cases for this: 
```rs
assert_eq!(to_valid_pkg_name("-2-123tau2ri-app-2"), "tau2ri-app-2");
assert_eq!(to_valid_pkg_name("1-2-3tau2ri-app2-"), "tau2ri-app2-");
```

**Review by amrbashir — CHANGES_REQUESTED** [review]

File: packages/cli/src/lib.rs (hunk 2 above)
Comment (amrbashir) [reply packages/cli/src/lib.rs:246]: nvm, looks like this is correct, I should read the `skip_while` documentation instead of guessing how it works by its name.

**Review by amrbashir — APPROVED** [review]
thank you!
